# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 08:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('commenter', models.CharField(blank=True, max_length=255, verbose_name='名前')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 6, 2, 8, 24, 53, 785470, tzinfo=utc), verbose_name='日付')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='日報タイトル')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='投稿者')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 6, 2, 8, 24, 53, 785470, tzinfo=utc), verbose_name='日付')),
                ('content', models.TextField(blank=True, verbose_name='日報')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='polls.Report', verbose_name='日報'),
        ),
    ]
